baseURL      = "http://localhost:1313/"
title        = "Virtual corner of Scott Kunkel"
languageCode = "en-us"
theme        = "hello-friend-ng"
[pagination]
  pagerSize = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  homeSubtitle = "Linguist • Researcher • Human being"

  disableReadOtherPosts = false
  enableSharingButtons  = true
  enableGlobalLanguageMenu = false

  description = "My new homepage or blog"
  keywords    = "homepage, blog"
  images      = [""]

  customCSS = ["css/custom.css"]

  enableThemeToggle = true 
  defaultTheme = "auto"

[params.favicon]
  # Path relative to /static
  logo = "favicon.ico"
  # Optional: SVG mask icon
  mask = "favicon-32x32.png"
  # Optional: Apple Touch icon
  appleTouchIcon = "apple-touch-icon.png"
  # Optional: Safari pinned tab color
  color = "#000000"

[[params.social]]
  name = "email"
  url  = "mailto:scott.kunkel@uni-konstanz.de"

[[params.social]]
  name = "researchgate"
  url  = "https://www.researchgate.net/profile/Scott-Kunkel"

[[params.social]]
  name = "googlescholar"
  url  = "https://scholar.google.com/citations?user=B-vSFV0AAAAJ&hl=en&oi=ao"

[taxonomies]
  category = "blog"
  tag      = "tags"
  series   = "series"

[languages]
  [languages.en]
    title     = "Scott Kunkel"
    keywords  = ""
    copyright = '© 2026 Scott Kunkel · Powered by <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a> · Theme: <a href="https://github.com/rhazdon/hugo-theme-hello-friend-ng" target="_blank" rel="noopener">hello-friend-ng</a>'

  [languages.en.params]
    subtitle = "Research"

    [languages.en.params.logo]
      logoText     = "Scott Kunkel – Academic webpage"
      logoHomeLink = "/"
      # Or use an image logo instead:
      # path = "/img/your-example-logo.svg"
      # alt  = "Your example logo alt text"

[[menu.main]]
  identifier = "about"
  name       = "About"
  url        = "/about/"
  weight     = 10

[[menu.main]]
  identifier = "projects"
  name       = "Projects"
  url        = "/projects/"
  weight     = 20

[[menu.main]]
  identifier = "cv"
  name       = "CV"
  url        = "/cv/"
  weight     = 30

 [[menu.main]]
   name = "Contact"
   url = "/contact/"
   weight = 40   
